apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dq99vd77s-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dq99vd77s-dotnet-basic-gitops